#!/bin/bash

./buildApp.sh -e BUILD_NUMBER=${GO_PIPELINE_LABEL} \
  -e PERFORM_BUILD=${PERFORM_BUILD} \
  -e GIT_COMMIT=${GO_REVISION} \
  -e SAUCE_PARENT_TUNNEL=${SAUCE_PARENT_TUNNEL} \
  -e SAUCE_TUNNEL_IDENTIFIER=${SAUCE_TUNNEL_IDENTIFIER} \
  -e SAUCE_USERNAME=${SAUCE_USERNAME} \
  -e SAUCE_ACCESS_KEY=${SAUCE_ACCESS_KEY} \
  -e AWS_ACCESS_KEY_ID_BINARIES=${AWS_ACCESS_KEY_ID_BINARIES} \
  -e AWS_SECRET_ACCESS_KEY_BINARIES=${AWS_SECRET_ACCESS_KEY_BINARIES} \
  -e UID=$(id -u) \
  -e GID=$(id -g)
